apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-a-to-b
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: service-b
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx # allow traffic only from ingress controller, so no traffic from service a
